---
# tasks file for hoplacloud.nginx_php
- name: Install Ondrej PHP PPA Repository
  apt_repository:
    repo: 'ppa:ondrej/php'

- name: Install Nginx PPA Repository
  apt_repository:
    repo: 'ppa:nginx/stable'
  when: ansible_distribution == 'Ubuntu'

- name: Install Nginx Official Repository
  apt_repository:
    repo: deb http://nginx.org/packages/debian/ {{ ansible_distribution_release }} nginx
  when: ansible_distribution == 'Debian'

- name: Install Nginx and PHP-FPM Packages
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - nginx
    - php{{ php_version }}-mbstring
    - php{{ php_version }}-mysql
    - php{{ php_version }}-xml
    - php{{ php_version }}-zip
    - php{{ php_version }}-gd
    - php{{ php_version }}-curl
    - php{{ php_version }}-bz2
    - php{{ php_version }}-fpm
    - php{{ php_version }}-intl
    - php{{ php_version }}-json
    - php-apcu

- name: Create new Nginx site directory index.html
  file:
    path: /usr/share/nginx/html/index.html
    state: absent

- name: Create new (empty) Nginx site directory index.html
  file:
    path: /usr/share/nginx/html/index.html
    state: touch
    mode: 0755

- name: Enable nginx service and start it
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Copy Configuration file
  copy:
    src: files/security.conf
    dest: /etc/nginx/conf.d/security.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx

- name: Ensure the vhost_deploy directory is present
  file:
    path: /usr/src/vhost_deploy_nginx
    state: directory

- name: Sending vhost_deploy_nginx file
  template:
    src: vhost_deploy.sh.j2
    dest: /usr/src/vhost_deploy_nginx/vhost_deploy.sh
    mode: '0755'

- name: Creating symlink for vhost_deploy.sh script
  file:
    src: /usr/src/vhost_deploy_nginx/vhost_deploy.sh
    dest: /usr/local/sbin/vhost_deploy
    state: link

- name: Sending the php.ini configuration file (FPM)
  template:
    src: php.ini.j2
    dest: /etc/php/{{ php_version }}/fpm/php.ini
  notify:
    - restart php-fpm

- name: Sending the php.ini configuration file (CLI)
  template:
    src: php.ini.j2
    dest: /etc/php/{{ php_version }}/cli/php.ini
  notify:
    - restart php-fpm

- name: Check if Composer is installed.
  stat:
    path: /usr/local/bin/composer
  register: composer_bin

- name: Get Composer installer signature.
  uri:
    url: https://composer.github.io/installer.sig
    return_content: true
  register: composer_installer_signature
  when: not composer_bin.stat.exists

- name: Download Composer installer.
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755
    checksum: "sha384:{{ composer_installer_signature.content }}"
  when: not composer_bin.stat.exists

- name: Run Composer installer.
  command: php /tmp/composer-installer.php --install-dir=/usr/local/bin --filename=composer
  when: not composer_bin.stat.exists

- name: Creating websites directory /var/www/sites
  file:
    path: /var/www/sites
    state: directory

- name: Creating home symlink to /var/www/sites
  file:
    src: /var/www
    dest: /home/{{ user_name }}/my_websites
    state: link
