---
- hosts: localhost
  vars:
    user_name: ubuntu
    mysql_packages:
      - mariadb-client
      - mariadb-server
      - python-mysqldb
  remote_user: root
  roles:
    - hoplacloud.vhostdeploy_nginx
    - geerlingguy.mysql
